uvmf:
  environments:
    dmem:
      agents:
      - initiator_responder: RESPONDER
        name: dmem_agent
        type: dmem
      analysis_components: []
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections: []
