uvmf:
  environments:
    lc3:
      agents:
      - initiator_responder: RESPONDER
        name: imem_agent
        type: imem
      - initiator_responder: RESPONDER
        name: dmem_agent
        type: dmem
      analysis_components:
      - name: imem_cov
        parameters: []
        type: imem_coverage
      - name: dmem_cov
        parameters: []
        type: dmem_coverage
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: fetch_env
        parameters: []
        reg_block_instance_name: fetch_env_rm
        type: fetch
      - name: decode_env
        parameters: []
        reg_block_instance_name: decode_env_rm
        type: decode
      - name: execute_env
        parameters: []
        reg_block_instance_name: execute_env_rm
        type: execute
      - name: writeback_env
        parameters: []
        reg_block_instance_name: writeback_env_rm
        type: writeback
      - name: memaccess_env
        parameters: []
        reg_block_instance_name: memaccess_env_rm
        type: memaccess
      - name: controller_env
        parameters: []
        reg_block_instance_name: controller_env_rm
        type: controller
      tlm_connections:
      - driver: imem_agent.monitored_ap
        receiver: imem_cov.imem_coverage_ae
        validate: 'True'
      - driver: dmem_agent.monitored_ap
        receiver: dmem_cov.dmem_coverage_ae
        validate: 'True'
