uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: dec_in_agent
        type: decode_in
      - initiator_responder: INITIATOR
        name: dec_out_agent
        type: decode_out
      analysis_components:
      - name: pred
        type: decode_predictor
      config_vars:
      - name: has_predictor
        type: bit
        isrand: 'False'
        value: '1'
      scoreboards:
      - name: scbd
        sb_type: uvmf_in_order_scoreboard
        trans_type: decode_out_transaction
      tlm_connections:
      - driver: dec_in_agent.monitored_ap
        receiver: pred.decode_in_ae
        validate: 'True'
      - driver: dec_out_agent.monitored_ap
        receiver: scbd.actual_analysis_export
        validate: 'True'
      - driver: pred.decode_out_ap
        receiver: scbd.expected_analysis_export
        validate: 'True'
