uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: decode_in_agent
        type: decode_in
      - initiator_responder: INITIATOR
        name: decode_out_agent
        type: decode_out
      analysis_components:
      - name: decode_pred
        parameters: []
        type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: decode_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
      - driver: decode_in_agent.monitored_ap
        receiver: decode_pred.decode_in_ae
        validate: 'True'
      - driver: decode_pred.decode_sb_ap
        receiver: decode_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: decode_out_agent.monitored_ap
        receiver: decode_scoreboard.actual_analysis_export
        validate: 'True'
