uvmf:
  environments:
    writeback:
      agents:
      - initiator_responder: INITIATOR
        name: writeback_in_agent
        type: writeback_in
      - initiator_responder: INITIATOR
        name: writeback_out_agent
        type: writeback_out
      analysis_components:
      - name: writeback_pred
        parameters: []
        type: writeback_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: writeback_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: writeback_out_transaction
      subenvs: []
      tlm_connections:
      - driver: writeback_in_agent.monitored_ap
        receiver: writeback_pred.writeback_in_ae
        validate: 'True'
      - driver: writeback_pred.writeback_sb_ap
        receiver: writeback_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: writeback_out_agent.monitored_ap
        receiver: writeback_scoreboard.actual_analysis_export
        validate: 'True'
