uvmf:
  environments:
    memaccess:
      agents:
      - initiator_responder: INITIATOR
        name: memaccess_in_agt
        type: memaccess_in
      - initiator_responder: RESPONDER
        name: memaccess_out_agt
        type: memaccess_out
      analysis_components:
      - name: memaccess_predictor
        parameters: []
        type: memaccess_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'False'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      - name: memaccess_in_pkg
      - name: memaccess_out_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: memaccess_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: memaccess_out_transaction
      subenvs: []
      tlm_connections:
      - driver: memaccess_in_agt.monitored_ap
        receiver: memaccess_predictor.memaccess_analysis_predictor_export
        validate: 'True'
      - driver: memaccess_predictor.memaccess_analysis_predictor_port
        receiver: memaccess_sb.expected_analysis_export
        validate: 'True'
      - driver: memaccess_out_agt.monitored_ap
        receiver: memaccess_sb.actual_analysis_export
        validate: 'True'
