uvmf:
  environments:
    decode:
      agents:
      - initiator_responder: INITIATOR
        name: dec_in_agent
        type: decode_in
      - initiator_responder: RESPONDER
        name: dec_out_agent
        type: decode_out
      analysis_components:
      - name: pred
        parameters: []
        type: decode_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_predictor
        type: bit
        value: '1'
      - comment: ''
        isrand: 'False'
        name: has_coverage
        type: bit
        value: '1'
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scbd
        sb_type: uvmf_in_order_scoreboard
        trans_type: decode_out_transaction
      subenvs: []
      tlm_connections:
      - driver: dec_in_agent.monitored_ap
        receiver: pred.decode_in_ae
        validate: 'True'
      - driver: dec_out_agent.monitored_ap
        receiver: scbd.actual_analysis_export
        validate: 'True'
      - driver: pred.decode_out_ap
        receiver: scbd.expected_analysis_export
        validate: 'True'
