uvmf:
  environments:
    fetch:
      agents:
      - initiator_responder: INITIATOR
        name: fetch_in_agent
        type: fetch_in
      - initiator_responder: RESPONDER
        name: fetch_out_agent
        type: fetch_out
      analysis_components:
      - name: fetch_predictor
        parameters: []
        type: fetch_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_predictor
        type: bit
        value: '1'
      - comment: ''
        isrand: 'False'
        name: has_coverage
        type: bit
        value: '1'
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: fetch_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: fetch_out_transaction
      subenvs: []
      tlm_connections:
      - driver: fetch_in_agent.monitored_ap
        receiver: fetch_predictor.analysis_export
        validate: 'True'
      - driver: fetch_predictor.analysis_port
        receiver: fetch_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: fetch_out_agent.monitored_ap
        receiver: fetch_scoreboard.actual_analysis_export
        validate: 'True'
