uvmf:
  environments:
    controller:
      agents:
      - initiator_responder: INITIATOR
        name: controller_in_agent
        type: controller_in
      - initiator_responder: INITIATOR
        name: controller_out_agent
        type: controller_out
      analysis_components:
      - name: controller_pred
        parameters: []
        type: controller_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: controller_scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: controller_out_transaction
      subenvs: []
      tlm_connections:
      - driver: controller_in_agent.monitored_ap
        receiver: controller_pred.controller_in_ae
        validate: 'True'
      - driver: controller_pred.controller_sb_ap
        receiver: controller_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: controller_out_agent.monitored_ap
        receiver: controller_scoreboard.actual_analysis_export
        validate: 'True'
