# Writeback environment
# No stages will have configuration variables
uvmf:
  environments:
    writeback:
      agents:
        - name: writeback_in_agent
          type: writeback_in
          initiator_responder: RESPONDER
        - name: writeback_out_agent
          type: writeback_out
          initiator_responder: RESPONDER
      # imports:
        # - name: lc3_prediction_pkg
      analysis_components:
        - name: writeback_pred
          type: writeback_predictor
      scoreboards:
        - name: writeback_sb
          sb_type: uvmf_in_order_scoreboard
          trans_type: writeback_out_transaction
      tlm_connections:
        - driver: writeback_in_agent.monitored_ap
          receiver: writeback_pred.writeback_in_agent_ae
          validate: 'True'
        - driver: writeback_pred.writeback_sb_ap
          receiver: writeback_sb.expected_analysis_export
          validate: 'True'
        - driver: writeback_out_agent.monitored_ap
          receiver: writeback_sb.actual_analysis_export
          validate: 'True'

          #

